### ISSUE TITLE
 Read from GeoTIFF - Detect masked values checkbox has no effect

### ISSUE THREAD

**Issue by BGovehovitch** [samthiriot/knime-shapefiles-as-WKT#88]
Checking the "Detect mask values" option seems to have to effect.
![image](https://user-images.githubusercontent.com/118716829/202989527-a21d01f2-cace-4e56-b747-10f9cf1cd14d.png)

![image](https://user-images.githubusercontent.com/118716829/202989844-51a60d14-d4ae-4b45-af74-ab2966a494fb.png)
-339,999,995,214,436,420,000,000,000,000,000,000,000 is the masked value in this case.

Here is a link to download the file (if need be): [https://files.eifer.kit.edu/nextcloud/s/2Hme2ntiLsGJGea](https://files.eifer.kit.edu/nextcloud/s/2Hme2ntiLsGJGea)

**Comment by samthiriot** [comment]
Thanks for this detailed bug report!

Your files are encoded as Float, so the min value representable is '1.401298464324817E-45'. The "missing" value in your file is '-3.3999999521443642E38'. This seems arbitrary...

I'll add an option so you can define another value.

**Comment by BGovehovitch** [comment]
Thank you! The option to set the value to skip works like a charm!
![image](https://user-images.githubusercontent.com/118716829/203245520-a98d2548-4226-491c-b40c-70d5b22decc3.png)

![image](https://user-images.githubusercontent.com/118716829/203245659-11c08ba2-253c-41e4-bc98-9fd2e9af0d73.png)
